### ISSUE TITLE
save_current_mesh always with double precision

### ISSUE THREAD

**Issue by adahbingee** [cnr-isti-vclab/PyMeshLab#163] opened 2021-11-10 02:56 UTC
I've checked [parameters](https://pymeshlab.readthedocs.io/en/latest/io_format_list.html#save-mesh-parameters).
There is no `property float` options.

MeshLab saved
```
ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 765821
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header
```

PyMeshLab saved
```
ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 765821
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header
```

code 

```python
import pymeshlab

ms = pymeshlab.MeshSet()
ms.load_new_mesh('longdress_vox10_1051.ply')
ms.save_current_mesh(file_name='binary.ply',
binary=True,
save_vertex_quality=False,
save_vertex_flag=False,
save_vertex_color=True,
save_vertex_coord=True,
save_vertex_normal=False,
save_vertex_radius=False,
save_face_quality=False,
save_face_flag=False,
save_face_color=False,
save_wedge_color=False,
save_wedge_texcoord=False,
save_wedge_normal=False
)
```

**Comment by alemuntoni** [comment] 2021-11-10 09:37
duplicate of #128

**Closed by alemuntoni** 2021-11-10 09:37 UTC
