### ISSUE TITLE
Error when installing pymeshlab on M1 mac

### ISSUE THREAD

**Issue by jabrucohee** [cnr-isti-vclab/PyMeshLab#210] opened 2022-04-25 13:53 UTC
Hey there, 

I tried installing pymeshlab on an M1 Mac, using pip3 install pymeshlab. This always threw in error during installation. After some googling I found the following alternativ command:

pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab

this installed pymeshlab on the second trial. When I then tried to import pymeshlab, I recieved the follwoing error

`
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/pymeshlab/_init_.py", line 11, in <module>
   from .pmeshlab import *
   ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'
   >>>
`

Could this be a bug ?

**Comment by alemuntoni** [comment] 2022-04-26 08:48
Hi, 
no, it is not a bug. M1 is just not supported right now, and installing via git does not include the compiled libraries in the pymeshlab package.
Closing because duplicate of #167.

**Closed by alemuntoni** 2022-04-26 08:48 UTC
