### ISSUE TITLE
How to export obj and that is writing the filename without the absolute path on Windows?

### ISSUE THREAD

**Issue by BigTsung** [cnr-isti-vclab/PyMeshLab#207] opened 2022-04-07 10:08 UTC
Hi guys, I'm not sure how to export an obj file and that is writing the filename without the absolute path. 
I try to use save_current_mesh to export an obj file and that works fine on macOS. But when I move the python script to Windows, the argument mtllib will include the absolute path. Does anyone also occur this issue on Windows? and any input?

**Comment by mumumomo** [comment] 2022-06-09 14:30
I also have this problem on Windows, it is very confusing, hope to fix it soon

**Comment by mumumomo** [comment] 2022-06-09 14:32
![image](https://user-images.githubusercontent.com/92135806/172872410-73fba829-07d6-4e1c-96b3-aeb9c70d5c5e.png)

**Comment by alemuntoni** [comment] 2022-06-14 07:40
Hi guys,
I'm quite busy in these days. 
This bug is on my priority list, but right now I don't have time to look into it. 
If someone needs desperately this bug solved, the source code is here. You can look into it, solve it and maybe send a pull request.
Otherwise, I'm sorry but you have to wait.

**Comment by mumumomo** [comment] 2022-06-14 07:48
> Hi guys, I'm quite busy in these days. This bug is on my priority list, but right now I don't have time to look into it. If someone needs desperately this bug solved, the source code is here. You can look into it, solve it and maybe send a pull request. Otherwise, I'm sorry but you have to wait.

Well, I hope you can fix this problem as soon as possible. Thanks for your reply

**Comment by methot-ilya-3ds** [comment] 2022-06-15 15:55
I found that you can work around this issue by doing the following:

Instead of saving with the output path you need to just use the file name. I was able to ensure that the file is saved to the correct location by temporarily changing the working directory to the place where I wanted to save the file.

```
os.chdir(output_path)
ms.save_current_mesh(file + ".obj")
os.chdir(original_path)
```

**Comment by mumumomo** [comment] 2022-06-16 06:34
> 我发现您可以通过执行以下操作来解决此问题：
> 
> 您只需使用文件名，而不是使用输出路径保存。通过临时将工作目录更改为我想要保存文件的位置，我能够确保将文件保存到正确的位置。
> 
> ```
> os.chdir(output_path)
> ms.save_current_mesh(file + ".obj")
> os.chdir(original_path)
> ```

Thank you very much, this solution works

**Comment by mumumomo** [comment] 2022-06-16 09:27
Can OBJ textures be exported to folders?

**Comment by mumumomo** [comment] 2022-06-16 11:49
![image](https://user-images.githubusercontent.com/92135806/174062845-7967778e-4c90-42df-9ca8-34b7ac39b9cb.png)
When I export mesh to a file, the map paths of the two MTL will be inconsistent ,Can someone tell me what this is about? thank you
![image](https://user-images.githubusercontent.com/92135806/174063360-1d67a090-82cb-4402-9834-163366508cd1.png)
![image](https://user-images.githubusercontent.com/92135806/174063421-129c86cf-8bcc-47a9-9d6a-50c5b63b3919.png)

**Comment by alemuntoni** [comment] 2022-06-28 13:23
I tried to replicate this issue, but I couldn't. 
Could you please share a piece of code that causes the problem? Thanks.

**Comment by mumumomo** [comment] 2022-06-28 13:38
> I tried to replicate this issue, but I couldn't. Could you please share a piece of code that causes the problem? Thanks.

The problem is that the problem is that using meshing_decimation_quadric_edge_collapse in a for loop and then saving it to a file can result in this 

Can I set the location of OBJ model maps and maps in MTL files myself ？

**Comment by alemuntoni** [comment] 2022-06-29 09:08
I cannot replicate the issue. I executed the exact code that you provided, and I obtain the mtl paths as expected:

```
####
#
# OBJ File Generated by Meshlab
#
####
# Object bunny10k_textured_20.obj
#
# Vertices: 1016
# Faces: 1999
#
####
mtllib ./bunny10k_textured_20.obj.mtl
```

Therefore, what's causing the problem could be:

- the input models
- the paths that you are giving as input of the script
- the way you are running the script

**Comment by mumumomo** [comment] 2022-06-29 09:15
> 
[testOBJ.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/9009106/testOBJ.zip)

难道是因为我的模型问题吗

**Comment by alemuntoni** [comment] 2022-06-29 09:29
Still cannot replicate the issue. 
I am using pymeshlab 2022.2 and calling:
```
python3 .\script.py
> inpath：C:\tmp\input
> outpath: C:\tmp\output
```
And, of course. in `C:\tmp\input` I put your input model.
If you are doing something different, please be as specific as possible.

**Comment by mumumomo** [comment] 2022-06-29 09:34
![image](https://user-images.githubusercontent.com/92135806/176403738-da55900b-994c-494e-9d36-a0f25f53b78c.png)

![image](https://user-images.githubusercontent.com/92135806/176403787-e425fc68-347d-4abc-a85c-97573e15e399.png)

Is the MTL file exported in your outpath different from mine?

**Comment by mumumomo** [comment] 2022-06-29 09:44
Ok, I got the idea. Ok, I got the idea. Thank you very much

**Comment by methot-ilya-3ds** [comment] 2022-06-30 13:55
Using Python Version 3.10.4 and PyMeshLab version 2022.2.post2

[Slice.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/9020317/Slice.zip)

Similar to @mumumomo I am simply using the following commands 

```
ms.load_new_mesh(ExportPath + "//" + FileName)

ms.save_current_mesh("My Directory Here" + "Name.obj", save_wedge_texcoord = True, save_vertex_color = False)
```

Hopefully this helps

**Comment by alemuntoni** [comment] 2022-07-01 12:28
Still cannot replicate it, I am sorry...
I am trying several scenarios, changing directory where python is executed, changing input and output directory... But none of these replicates the issue.
I guess that this could depend on some system setup? If someone has some clues...

I've also tried to make a small change in my fork that could solve this issue (but without the ability to replicate it, it is hard to tell...)
If someone wants to try, the nightly is available [here](https://github.com/alemuntoni/PyMeshLab/actions), and instructions on how to install it are [here](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-install-the-last-nightly-version). It would be really appreciated, thanks!!

**Comment by methot-ilya-3ds** [comment] 2022-07-01 19:09
The problem has also disappeared for me. I tried it after having installed your fix @alemuntoni and I've tried reverting back to the earlier python version to see if the problem returns but it did not.

A blessing for me, but a curse for solving the problem.

**Comment by alemuntoni** [comment] 2022-07-04 10:18
Well, yes.. I'll apply anyway the fix, just hoping that it solves the issue for everybody.

**Closed** 2022-10-15 18:07 UTC
Labels: wontfix
