### ISSUE TITLE
How to save snapshots of the cloud points?

### ISSUE THREAD

**Issue by hwj05140514** [cnr-isti-vclab/PyMeshLab#230] opened 2022-07-01 03:14 UTC
Hello, I got a problem when I wanted to apply the filter ,"save_snapshot" to the cloud points. The error was "number of vertices less than three or zero number of faces on selected mesh". I loaded the cloud points from ".txt" file，only containing "x,y,z" information. Does it mean I can't take  snapshots on the cloud points?

**Comment by hwj05140514** [comment] 2022-07-06 05:28
> 

OK.Thanks.

**Comment by alemuntoni** [comment] 2022-10-17 13:28
Closing as duplicate of #164. Refer to that issue for further details.

**Closed by alemuntoni** 2022-10-17 13:28 UTC
Labels: enhancement
