### ISSUE TITLE
install PyMeshLab on m1 Mac

### ISSUE THREAD

**Issue by LouisSY** [cnr-isti-vclab/PyMeshLab#276] opened 2023-01-15 16:36 UTC
May I ask if PyMeshLab can be successfully installed and run on Mac with Apple Silicon? If so, how can I install PyMeshLab?

**Comment by alemuntoni** [comment] 2023-01-16 10:23
Duplicate of #167. Will be available when github actions will allow runs on Apple M1, and when we will have MeshLab working with Qt6.

**Closed by alemuntoni** 2023-01-16 10:23 UTC

**Comment by saching13** [comment] 2023-11-12 10:34
@alemuntoni  it seems to be available. Is it added ?
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/#:~:text=Speed%20up%20your%20GitHub%20Actions,macOS%20larger%20runner%20for%20arm64.&text=Today%2C%20GitHub%20is%20releasing%20a,larger%20runner%20for%20GitHub%20Actions.

**Comment by alemuntoni** [comment] 2023-11-15 08:26
@saching13 nope. Large m1 runners are available only for paying accounts.
