### ISSUE TITLE
Error in saving ply file in binary format

### ISSUE THREAD

**Issue by LindaGuiducci** [cnr-isti-vclab/PyMeshLab#31] opened 2020-12-14 09:42 UTC
When saving a file in binary ply format, it can't be read by meshlab: given error is "bad vertex index in face".

**Comment by alemuntoni** [comment] 2020-12-14 09:44
Duplicate of #28. It has been already solved and it will be available in the next pymeshlab version (soon!).

**Closed by alemuntoni** 2020-12-14 09:44 UTC
