### ISSUE TITLE
Filter Compute Geometric Measures: Does not return inertia tensor

### ISSUE THREAD

**Issue by vincentmaye** [cnr-isti-vclab/PyMeshLab#48] opened 2021-01-19 10:39 UTC
Hi,

first of all great library really makes things easier! I am trying to get the inertia tensor from a mesh (the mesh is a convex hull) directly in python. Unfortunately if I run:

`    out_dict = ms.apply_filter('compute_geometric_measures')
`

the out_dict does not contain any inertia entry. Computing the inertia for the same mesh in the Meshlab GUI works fine.

**Comment by alemuntoni** [comment] 2021-01-20 13:16
Closing because duplicate of #39. 
I am confident that this feature will be available in the next version of pymeshlab.

**Closed by alemuntoni** 2021-01-20 13:16 UTC
