### ISSUE TITLE
Error details: Bad vertex index in face

### ISSUE THREAD

**Issue by shengchiliu** [cnr-isti-vclab/PyMeshLab#38] opened 2020-12-17 16:47 UTC
I run the example code (test_save_filter_script.py), but got an error
`Error details: Bad vertex index in face`
I use MacOS, btw.

**Comment by alemuntoni** [comment] 2020-12-17 17:26
duplicate of #28 and #31.
It is already solved, I'll release the new version as soon as possible (hopefully tomorrow).

**Closed by alemuntoni** 2020-12-17 17:26 UTC
