### ISSUE TITLE
turn_into_a_pure_triangular_mesh

### ISSUE THREAD

**Issue by danielegrandi-adsk** [cnr-isti-vclab/PyMeshLab#131] opened 2021-08-11 19:19 UTC
Hello,

I'm having issues using the turn_into_a_pure_triangular_mesh filter, it doesn't seem to be working?

Here is my code:
```
import pymeshlab


ms = pymeshlab.MeshSet()
ms.load_new_mesh('a.obj')

ms.save_current_mesh('a_no_filter.ply', save_vertex_normal=True, binary=False)

ms.turn_into_a_pure_triangular_mesh()
ms.save_current_mesh('a_triangles.ply', save_vertex_normal=True, binary=False)
```

There seems to be a difference in the precision of the output coordinates?
I'm attaching the test mesh and the outputs.
Thanks!

[meshes.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/6970868/meshes.zip)
[a_ui triangles.zip, the result I get with the UI when applying the filter](https://github.com/cnr-isti-vclab/PyMeshLab/files/6972082/a_ui.triangles.zip)

**Comment by alemuntoni** [comment] 2021-08-18 08:03
Duplicate of #128.
pymeshlab uses floating point with double precision (as well as python), and it is based on meshlab 2021.7**d**.

**Closed by alemuntoni** 2021-08-18 08:03 UTC

**Comment by danielegrandi-adsk** [comment] 2021-08-18 15:55
Thank you for the explanation and support.
